# Generated by Django 6.0 on 2026-03-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="service",
            table="services",
        ),
    ]
