# Generated by Django 6.0 on 2026-01-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("cust_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=150, unique=True)),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("address", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customers",
                "managed": False,
            },
        ),
    ]
