# Generated by Django 6.0 on 2026-03-04 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("invoice_id", models.AutoField(primary_key=True, serialize=False)),
                ("invoice_number", models.CharField(max_length=20, unique=True)),
                (
                    "invoice_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "invoices",
                "managed": False,
            },
        ),
    ]
