# Generated by Django 6.0 on 2026-01-07 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                ("color_id", models.AutoField(primary_key=True, serialize=False)),
                ("color_code", models.CharField(max_length=20)),
                ("color_name", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Color",
                "verbose_name_plural": "Colors",
                "db_table": "colors",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("offer_id", models.AutoField(primary_key=True, serialize=False)),
                ("offer_name", models.CharField(max_length=50)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
            ],
            options={
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
                "db_table": "offers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_qty", models.IntegerField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("image_url", models.ImageField(upload_to="products/")),
                ("alt_text", models.CharField(max_length=50)),
                ("is_primary", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "db_table": "product_images",
                "managed": False,
            },
        ),
    ]
